<div class="custom-block_footer">
    <img src="<?php echo $block->getViewFileUrl('images/footer.svg') ?>" alt="Company Logo" class="company-logo">
    <div class="company-info">
        <h2>Contacts</h2>
        <p>Become a Client</p>
        <p>+1 312-239-0843</p>
        <p>order@perspectiveteam.com</p>
        <p>Find us</p>
        <p>Kyiv, 15a Tumaniana</p>
        <a href="https://perspectiveteam.com">perspectiveteam.com</a>
    </div>
</div>
